name: CI/CD VideoEditor Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build backend Docker image
        run: |
          docker build -t videoeditor-backend:latest -f backend/Dockerfile.backend .

      - name: Build frontend Docker image
        run: |
          docker build -t videoeditor-frontend:latest -f frontend/Dockerfile.frontend .

      - name: Start backend container
        run: |
          docker run -d --name videoeditor-backend -p 5000:5000 videoeditor-backend:latest

      - name: Wait for backend
        run: |
          echo "Waiting for backend..."
          timeout 30s bash -c 'until curl -sf http://localhost:5000/api/progress; do sleep 1; done'


      - name: Security Scan - Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "videoeditor-backend:latest"
          format: "table"
          exit-code: "1"
          vuln-type: "os,libary"
          severity: "CRITICAL,HIGH"

      - name: Security Scan - Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "videoeditor-frontend:latest"
          format: "table"
          exit-code: "1"
          vuln-type: "os,libary"
          severity: "CRITICAL,HIGH"

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"

      # - name: Install backend dependencies
      #   run: |
      #     pip install -r requirements.txt
      #     pip install pytest requests

      # - name: Run backend tests
      #   run: |
      #     pytest testing_folder -q
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag + Push backend image
        run: |
          docker tag videoeditor-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-backend:latest

      - name: Tag + Push frontend image
        run: |
          docker tag videoeditor-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-frontend:latest


  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /app
            cd /app

            echo "Pulling latest images..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/videoeditor-frontend:latest

            echo "Stopping old containers..."
            docker compose down

            echo "Starting new containers..."
            docker compose up -d --build

            echo "Cleaning old unused images..."
            docker image prune -f
